ALTER TABLE barbers
  ADD COLUMN IF NOT EXISTS stand_type TEXT NOT NULL DEFAULT 'individual';

CREATE TABLE IF NOT EXISTS barber_team_members (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barber_id INTEGER NOT NULL REFERENCES barbers(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  title TEXT DEFAULT 'Barber',
  bio TEXT DEFAULT '',
  image TEXT DEFAULT '',
  specialties TEXT DEFAULT '',
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS team_member_id INTEGER DEFAULT NULL REFERENCES barber_team_members(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_barber_team_members_barber_id
  ON barber_team_members(barber_id);

DROP INDEX IF EXISTS uniq_active_booking_slot;

CREATE UNIQUE INDEX IF NOT EXISTS uniq_active_booking_slot_member
  ON bookings(barber_id, booking_date, booking_time, COALESCE(team_member_id, 0))
  WHERE status IN ('pending','confirmed');
