ALTER TABLE barber_services ADD COLUMN IF NOT EXISTS category TEXT DEFAULT '';
ALTER TABLE barber_services ADD COLUMN IF NOT EXISTS description TEXT DEFAULT '';
ALTER TABLE barber_services ADD COLUMN IF NOT EXISTS is_available INTEGER NOT NULL DEFAULT 1;
ALTER TABLE barber_services ADD COLUMN IF NOT EXISTS image TEXT DEFAULT '';
