CREATE TABLE IF NOT EXISTS customer_subscriptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tier TEXT NOT NULL DEFAULT 'PREMIUM',
  price DOUBLE PRECISION NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'pending',
  billing_cycle TEXT NOT NULL DEFAULT 'monthly',
  amount_paid DOUBLE PRECISION NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'UGX',
  payment_status TEXT NOT NULL DEFAULT 'pending',
  payment_reference TEXT DEFAULT '',
  provider TEXT DEFAULT 'internal',
  started_at TEXT DEFAULT NOW(),
  expires_at TEXT DEFAULT NULL,
  activated_at TEXT DEFAULT NULL,
  created_at TEXT DEFAULT NOW(),
  updated_at TEXT DEFAULT NOW()
);

ALTER TABLE payment_transactions
  ADD COLUMN IF NOT EXISTS customer_subscription_id INTEGER DEFAULT NULL REFERENCES customer_subscriptions(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_customer_subscriptions_user_status
  ON customer_subscriptions(user_id, status);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_customer_subscription_id
  ON payment_transactions(customer_subscription_id);
