CREATE TABLE IF NOT EXISTS admin_audit_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_user_id INTEGER DEFAULT NULL REFERENCES users(id) ON DELETE SET NULL,
  admin_username TEXT DEFAULT '',
  action_type TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id TEXT NOT NULL,
  old_value TEXT DEFAULT '{}',
  new_value TEXT DEFAULT '{}',
  reason TEXT DEFAULT '',
  created_at TEXT DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_log_action
  ON admin_audit_log(action_type, target_type, created_at);
