CREATE TABLE IF NOT EXISTS notification_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token TEXT NOT NULL UNIQUE,
  platform TEXT DEFAULT 'web',
  browser TEXT DEFAULT '',
  device_label TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  last_used_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_notification_tokens_token
  ON notification_tokens(token);

CREATE INDEX IF NOT EXISTS idx_notification_tokens_user_id
  ON notification_tokens(user_id);
