-- Migration 033: Subscription reminder events
-- Tracks which expiry reminder notifications have been sent per subscription
-- to prevent duplicate alerts at 7d / 3d / 1d / expired milestones.

CREATE TABLE IF NOT EXISTS subscription_reminder_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- 'provider' or 'customer'
  account_scope TEXT NOT NULL DEFAULT 'provider',
  -- FK to the relevant subscription row (nullable if record deleted)
  subscription_id INTEGER DEFAULT NULL,
  -- 'reminder_7d' | 'reminder_3d' | 'reminder_1d' | 'expiry_notice'
  event_type TEXT NOT NULL,
  sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- ISO expiry date at time of send, for deduplication
  expiry_snapshot TEXT DEFAULT NULL,
  metadata TEXT DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_sub_reminders_user_scope_event
  ON subscription_reminder_events(user_id, account_scope, event_type);

CREATE INDEX IF NOT EXISTS idx_sub_reminders_sent_at
  ON subscription_reminder_events(sent_at);

-- Also add a last_reminder_job_at column to track job runs (optional sentinel table)
CREATE TABLE IF NOT EXISTS subscription_job_runs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_name TEXT NOT NULL,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finished_at TIMESTAMPTZ DEFAULT NULL,
  records_processed INTEGER DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'running',
  error_message TEXT DEFAULT NULL
);
