-- Security/business audit trail. Separate from the legacy `audit_logs` (user_id +
-- action) and `admin_audit_log` tables so existing writers/readers keep working.
-- Stores only hashed IP / user-agent and sanitized, redacted metadata — never raw
-- tokens, passwords, OTPs, payment credentials, or message contents.
CREATE TABLE IF NOT EXISTS security_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  actor_user_id INTEGER DEFAULT NULL REFERENCES users(id) ON DELETE SET NULL,
  actor_role TEXT DEFAULT NULL,
  target_type TEXT DEFAULT NULL,
  target_id TEXT DEFAULT NULL,
  ip_hash TEXT DEFAULT NULL,
  user_agent_hash TEXT DEFAULT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_security_audit_created_at ON security_audit_logs (created_at);
CREATE INDEX IF NOT EXISTS idx_security_audit_event_type ON security_audit_logs (event_type);
CREATE INDEX IF NOT EXISTS idx_security_audit_actor ON security_audit_logs (actor_user_id);
CREATE INDEX IF NOT EXISTS idx_security_audit_target ON security_audit_logs (target_type, target_id);
