CREATE INDEX IF NOT EXISTS idx_favorites_user ON favorites(user_id);
CREATE INDEX IF NOT EXISTS idx_favorites_barber ON favorites(barber_id);

CREATE TABLE IF NOT EXISTS customer_slot_alerts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  existing_booking_id INTEGER REFERENCES bookings(id) ON DELETE SET NULL,
  provider_id INTEGER NOT NULL REFERENCES barbers(id) ON DELETE CASCADE,
  service_id INTEGER NOT NULL REFERENCES barber_services(id) ON DELETE CASCADE,
  desired_start_date DATE NOT NULL,
  desired_end_date DATE NOT NULL,
  preferred_time_start TIME NOT NULL,
  preferred_time_end TIME NOT NULL,
  current_booking_date DATE,
  current_booking_time TIME,
  notification_preference TEXT NOT NULL DEFAULT 'in_app',
  status TEXT NOT NULL DEFAULT 'active',
  expires_at TIMESTAMPTZ NOT NULL,
  last_evaluated_at TIMESTAMPTZ,
  matched_slot_id TEXT,
  candidate_time TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT chk_customer_slot_alert_status
    CHECK (status IN ('active', 'paused', 'matched', 'expired', 'cancelled')),
  CONSTRAINT chk_customer_slot_alert_time_window
    CHECK (preferred_time_end > preferred_time_start),
  CONSTRAINT chk_customer_slot_alert_date_window
    CHECK (desired_end_date >= desired_start_date),
  CONSTRAINT chk_customer_slot_alert_notification
    CHECK (notification_preference IN ('in_app', 'push'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_active_customer_slot_alert
ON customer_slot_alerts (
  customer_user_id,
  provider_id,
  service_id,
  desired_start_date,
  desired_end_date,
  preferred_time_start,
  preferred_time_end
)
WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_customer_slot_alerts_user_status
ON customer_slot_alerts(customer_user_id, status);

CREATE INDEX IF NOT EXISTS idx_customer_slot_alerts_provider_service
ON customer_slot_alerts(provider_id, service_id, status);
