CREATE TABLE IF NOT EXISTS provider_promotions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barber_id INTEGER NOT NULL REFERENCES barbers(id) ON DELETE CASCADE,
  service_id INTEGER NOT NULL REFERENCES barber_services(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT DEFAULT '',
  discount_type TEXT NOT NULL,
  discount_value NUMERIC(12, 2) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  usage_limit INTEGER,
  per_customer_limit INTEGER,
  eligible_customer_group TEXT DEFAULT 'all',
  status TEXT NOT NULL DEFAULT 'draft',
  created_by_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT chk_provider_promotion_discount_type CHECK (discount_type IN ('fixed', 'percentage')),
  CONSTRAINT chk_provider_promotion_discount_value CHECK (discount_value > 0),
  CONSTRAINT chk_provider_promotion_dates CHECK (end_date >= start_date),
  CONSTRAINT chk_provider_promotion_status CHECK (status IN ('draft', 'active', 'paused', 'expired', 'cancelled'))
);

CREATE INDEX IF NOT EXISTS idx_provider_promotions_barber_status
ON provider_promotions(barber_id, status, start_date, end_date);

CREATE INDEX IF NOT EXISTS idx_provider_promotions_service
ON provider_promotions(service_id, status);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_provider_active_promotion_title
ON provider_promotions(barber_id, service_id, title)
WHERE status = 'active';
